theme: jekyll-theme-architect
title: Gender Pay Gap
description: Tracing the online discussion on Gender Pay Gap through YouTube comments
menu: [
{'name': 'Home', 'pagename': 'index'},
{'name': 'sharks here !', 'pagename': 'page1'},
{'name': 'Go there', 'pagename': 'page2'},
{'name': 'Yet Another page', 'pagename': 'page3'},
]
